apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fiber
  namespace: go-fiber
  labels:
    app: go-fiber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-fiber
  template:
    metadata:
      labels:
        app: go-fiber
    spec:
      containers:
      - name: go-fiber
        image: go-fiber
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: Always
